services:
  app:
    image: ${DOCKERHUB_USERNAME}/issuer-app:latest
    container_name: issuer-app
    ports:
      - "8000:8000"
    environment:
      NAVER_API_CLIENT_ID: ${NAVER_API_CLIENT_ID}
      NAVER_API_CLIENT_SECRET: ${NAVER_API_CLIENT_SECRET}
      CLOVA_API_CLIENT_ID: ${CLOVA_API_CLIENT_ID}
      CLOVA_API_CLIENT_SECRET: ${CLOVA_API_CLIENT_SECRET}
      CLOVA_CHAT_COMPLETION_CLIENT_KEY: ${CLOVA_CHAT_COMPLETION_CLIENT_KEY}
      CLOVA_CHAT_COMPLETION_CLIENT_KEY_PRIMARY_VAR: ${CLOVA_CHAT_COMPLETION_CLIENT_KEY_PRIMARY_VAR}
      CLOVA_CHAT_COMPLETION_REQUEST_ID: ${CLOVA_CHAT_COMPLETION_REQUEST_ID}
      CLOVA_EMBEDDING_CLIENT_KEY: ${CLOVA_EMBEDDING_CLIENT_KEY}
      CLOVA_EMBEDDING_CLIENT_KEY_PRIMARY_VAR: ${CLOVA_EMBEDDING_CLIENT_KEY_PRIMARY_VAR}
      CLOVA_EMBEDDING_REQUEST_ID: ${CLOVA_EMBEDDING_REQUEST_ID}
      CLOVA_SUMMARY_CLIENT_KEY: ${CLOVA_SUMMARY_CLIENT_KEY}
      CLOVA_SUMMARY_CLIENT_KEY_PRIMARY_VAR: ${CLOVA_SUMMARY_CLIENT_KEY_PRIMARY_VAR}
      CLOVA_SUMMARY_REQUEST_ID: ${CLOVA_SUMMARY_REQUEST_ID}
      CLOVA_CHAT_COMPLETION_003_CLIENT_KEY: ${CLOVA_CHAT_COMPLETION_003_CLIENT_KEY}
      CLOVA_CHAT_COMPLETION_003_CLIENT_KEY_PRIMARY_VAR: ${CLOVA_CHAT_COMPLETION_003_CLIENT_KEY_PRIMARY_VAR}
      CLOVA_CHAT_COMPLETION_003_CLIENT_KEY_REQUEST_ID: ${CLOVA_CHAT_COMPLETION_003_CLIENT_KEY_REQUEST_ID}
      NAVER_AD_API_KEY: ${NAVER_AD_API_KEY}
      NAVER_AD_SECRET_KEY: ${NAVER_AD_SECRET_KEY}
      NAVER_AD_CUSTOMER_ID: ${NAVER_AD_CUSTOMER_ID}
      CLOVA_EMBEDDING_V2_REQUEST_ID: ${CLOVA_EMBEDDING_V2_REQUEST_ID}
      REDIS_OM_URL: redis://redis:6379
      TZ: Asia/Seoul
    networks:
      - issuer-app-network
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - issuer-app-network

networks:
  issuer-app-network:
    driver: bridge