version: '3.8'

services:
  app:
    image: ${DOCKERHUB_USERNAME}/issuer-app:latest
    ports:
      - "8000:8000"
    environment:
      NAVER_API_CLIENT_ID: ${NAVER_API_CLIENT_ID}
      NAVER_API_CLIENT_SECRET: ${NAVER_API_CLIENT_SECRET}
      CLOVA_API_CLIENT_ID: ${CLOVA_API_CLIENT_ID}
      CLOVA_API_CLIENT_SECRET: ${CLOVA_API_CLIENT_SECRET}
      CLOVA_CHAT_COMPLETION_CLIENT_KEY: ${CLOVA_CHAT_COMPLETION_CLIENT_KEY}
      CLOVA_CHAT_COMPLETION_CLIENT_KEY_PRIMARY_VAR: ${CLOVA_CHAT_COMPLETION_CLIENT_KEY_PRIMARY_VAR}
      CLOVA_CHAT_COMPLETION_REQUEST_ID: ${CLOVA_CHAT_COMPLETION_REQUEST_ID}
      CLOVA_EMBEDDING_CLIENT_KEY: ${CLOVA_EMBEDDING_CLIENT_KEY}
      CLOVA_EMBEDDING_CLIENT_KEY_PRIMARY_VAR: ${CLOVA_EMBEDDING_CLIENT_KEY_PRIMARY_VAR}
      CLOVA_EMBEDDING_REQUEST_ID: ${CLOVA_EMBEDDING_REQUEST_ID}
      CLOVA_SUMMARY_CLIENT_KEY: ${CLOVA_SUMMARY_CLIENT_KEY}
      CLOVA_SUMMARY_CLIENT_KEY_PRIMARY_VAR: ${CLOVA_SUMMARY_CLIENT_KEY_PRIMARY_VAR}
      CLOVA_SUMMARY_REQUEST_ID: ${CLOVA_SUMMARY_REQUEST_ID}
      CLOVA_CHAT_COMPLETION_003_CLIENT_KEY: ${CLOVA_CHAT_COMPLETION_003_CLIENT_KEY}
      CLOVA_CHAT_COMPLETION_003_CLIENT_KEY_PRIMARY_VAR: ${CLOVA_CHAT_COMPLETION_003_CLIENT_KEY_PRIMARY_VAR}
      CLOVA_CHAT_COMPLETION_003_CLIENT_KEY_REQUEST_ID: ${CLOVA_CHAT_COMPLETION_003_CLIENT_KEY_REQUEST_ID}

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"