from app.request_external_api.request_news import RequestNews
from app.request_external_api.request_suggestions import RequestSuggestions
from app.request_external_api.request_trend import RequestTrend
from app.request_external_api.request_news_comments import RequestNewsComments
from app.request_external_api.request_news_summary import get_news_summary
