name: Build and Deploy with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # 1. Python 3.10 세팅
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 2. 의존성 캐시
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 3. 의존성 설치 및 애플리케이션 테스트
      - name: Install dependencies and run tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # pytest  # Uncomment and configure your tests

      # 4. Docker 이미지 빌드
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/issuer-app:latest .

      # 5. DockerHub 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 6. Docker Hub 이미지 푸시
      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/issuer-app:latest

      # 7. 원격 서버에 SSH로 접속하여 Docker 이미지 업데이트 및 실행
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/issuer-app:latest
            docker stop issuer-app || true
            docker rm issuer-app || true
            docker run -d --name issuer-app -p 80:80 \
              -e NAVER_API_CLIENT_ID=${{ secrets.NAVER_API_CLIENT_ID }} \
              -e NAVER_API_CLIENT_SECRET=${{ secrets.NAVER_API_CLIENT_SECRET }} \
              -e CLOVA_API_CLIENT_ID=${{ secrets.CLOVA_API_CLIENT_ID }} \
              -e CLOVA_API_CLIENT_SECRET=${{ secrets.CLOVA_API_CLIENT_SECRET }} \
              -e CLOVA_CHAT_COMPLETION_CLIENT_KEY=${{ secrets.CLOVA_CHAT_COMPLETION_CLIENT_KEY }} \
              -e CLOVA_CHAT_COMPLETION_CLIENT_KEY_PRIMARY_VAR=${{ secrets.CLOVA_CHAT_COMPLETION_CLIENT_KEY_PRIMARY_VAR }} \
              -e CLOVA_CHAT_COMPLETION_REQUEST_ID=${{ secrets.CLOVA_CHAT_COMPLETION_REQUEST_ID }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/issuer-app:latest
            docker image prune -af
